# Header
menu:
  主页: /blog/
  所有文章: /blog/archives
  # 随笔: /blog/tags/随笔
  标签云: /blog/tags
  关于我: /blog/2015/11/02/about/

# SubNav
subnav:
  # RSS plugin: https://github.com/hexojs/hexo-generator-feed
  # Encrypt email 加密邮件地址 http://tool.chacuo.net/commonhideinfo
  Email: "mailto:piniing@qq.com"
  #新浪微博: "sina weibo"
  GitHub: "http://github.com/piniing"
  #V2EX: "#"
  RSS: "/blog/atom.xml"
  #知乎: "zhihu"
  #豆瓣: "douban"
  #Facebook: "#"
  #Google: "#"
  #Twitter: "#"
  #LinkedIn: "#"
  #QQ: "#"
  #微信: "Wechat"
  #PayPal: "#"
  #StackOverflow: "#"
  #Instagram: "#"
  #Flickr: "#"

# Customize feed link 自定义订阅地址
rss: /blog/atom.xml

# true: 个性图片背景, false: 淳朴灰白背景
background_image: false

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
#google_analytics: ''
favicon: /blog/favicon.png

#你的头像url
avatar: http://7xnw9f.com1.z0.glb.clouddn.com/IMG_0222.JPG?imageView2/1/2/180/h/180

#是否开启分享
share: true

#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#注册多说后，地址前面的就是你的 duoshuo-key http://duoshuo-key.duoshuo.com
duoshuo: piniing

#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  Hexo: https://hexo.io
  GitHub: https://pages.github.com/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: false

#是否显示边栏中的搜索框 
#Search Box in left column
#search_box: true
